# Generated by Django 6.0.4 on 2026-04-29 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlantReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField()),
                ('air_humidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('light_level', models.FloatField()),
                ('health_score', models.FloatField(blank=True, null=True)),
                ('health_status', models.CharField(blank=True, max_length=50, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='AIAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plants.plantreading')),
            ],
        ),
    ]
